# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-06 21:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='', max_length=35)),
                ('jabatan', models.CharField(default='', max_length=40)),
                ('fakultas', models.CharField(default='', max_length=40)),
                ('prodi', models.CharField(default='', max_length=40)),
                ('nik', models.CharField(default='', max_length=10, verbose_name='NIK')),
                ('alamat', models.TextField(default='', max_length=300)),
                ('TanggalLahir', models.DateField(default='', verbose_name='Tanggal Lahir (ex : 1995-01-05)')),
                ('tgl_daftar', models.DateField(default='')),
                ('daftar', models.BooleanField(default=False)),
                ('akun', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
