# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-08 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_hasil_kalkulasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hasil_kalkulasi',
            name='validasi',
        ),
    ]
