# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-10 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_data_member_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hasil_kalkulasi',
            name='tidak_diterima',
        ),
        migrations.AddField(
            model_name='hasil_kalkulasi',
            name='fakultas',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hasil_kalkulasi',
            name='prodi',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hasil_kalkulasi',
            name='akun',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
