# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-16 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_berita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berita',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='berita',
            name='publish',
        ),
    ]
