# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-16 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20170117_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='berita',
            old_name='user',
            new_name='author',
        ),
    ]
