# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-16 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20170117_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
