# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-17 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_pesan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesan',
            name='penerima',
            field=models.IntegerField(default=0),
        ),
    ]
