# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-17 15:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0012_pesan_penerima'),
    ]

    operations = [
        migrations.CreateModel(
            name='pesan_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjek', models.CharField(default='', max_length=120)),
                ('penerima', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('dibaca', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='pesan_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjek', models.CharField(default='', max_length=120)),
                ('content', models.TextField()),
                ('dibaca', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pengirim', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='pesan',
            name='pengirim',
        ),
        migrations.DeleteModel(
            name='pesan',
        ),
    ]
