# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-21 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_timeline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeline',
            old_name='judul1',
            new_name='j_pendaftaran',
        ),
        migrations.RenameField(
            model_name='timeline',
            old_name='judul2',
            new_name='j_penerimaan',
        ),
        migrations.RenameField(
            model_name='timeline',
            old_name='judul3',
            new_name='j_pengumuman',
        ),
        migrations.RenameField(
            model_name='timeline',
            old_name='judul4',
            new_name='j_review',
        ),
        migrations.RenameField(
            model_name='timeline',
            old_name='judul5',
            new_name='j_seleksi',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='content4',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='content5',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='content6',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='judul6',
        ),
        migrations.AddField(
            model_name='timeline',
            name='c_pendaftaran',
            field=models.TextField(default='', max_length=320),
        ),
        migrations.AddField(
            model_name='timeline',
            name='c_penerimaan',
            field=models.TextField(default='', max_length=320),
        ),
        migrations.AddField(
            model_name='timeline',
            name='c_pengumuman',
            field=models.TextField(default='', max_length=320),
        ),
        migrations.AddField(
            model_name='timeline',
            name='c_review',
            field=models.TextField(default='', max_length=320),
        ),
        migrations.AddField(
            model_name='timeline',
            name='c_seleksi',
            field=models.TextField(default='', max_length=320),
        ),
        migrations.AddField(
            model_name='timeline',
            name='tahun_penerimaan',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
