# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-22 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20170122_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='t_pendaftaran',
            field=models.TextField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='timeline',
            name='t_penerimaan',
            field=models.TextField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='timeline',
            name='t_pengumuman',
            field=models.TextField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='timeline',
            name='t_review',
            field=models.TextField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='timeline',
            name='t_seleksi',
            field=models.TextField(default='', max_length=45),
        ),
    ]
