# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-22 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20170122_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
