# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-22 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20170123_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_member',
            name='bukti_pot',
            field=models.ImageField(default='', upload_to='upload/bukti_pot', verbose_name='Bukti Pendapatan Orang Tua. Ex : Slip Gaji'),
        ),
        migrations.AddField(
            model_name='data_member',
            name='bukti_tan',
            field=models.ImageField(default='', upload_to='upload/bukti_tan', verbose_name='Bukti Tanggungan Orang Tua. ex : Kartu Keluarga'),
        ),
    ]
