# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-22 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20170123_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_member',
            name='telepon',
            field=models.CharField(default='', max_length=18, null=True),
        ),
    ]
