# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-29 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_data_member_telepon'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasil_kalkulasi',
            name='tunggu',
            field=models.BooleanField(default=True),
        ),
    ]
