# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-30 12:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='data_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='', max_length=35)),
                ('fakultas', models.CharField(default='', max_length=40)),
                ('prodi', models.CharField(default='', max_length=40)),
                ('nim', models.CharField(default='', max_length=10, verbose_name='NIM')),
                ('ktm', models.ImageField(default='', upload_to='upload/ktm', verbose_name='KTM')),
                ('alamat', models.TextField(default='', max_length=300)),
                ('TanggalLahir', models.DateField(default='', verbose_name='Tanggal Lahir (ex : 1995-01-05)')),
                ('semester', models.IntegerField(default='', verbose_name='Semester')),
                ('ipk', models.FloatField(default='', max_length=5, verbose_name='IPK')),
                ('transkrip', models.ImageField(default='', upload_to='upload/transkrip', verbose_name='Transkrip Nilai')),
                ('tan', models.FloatField(default='', verbose_name='Tanggungan Orang Tua')),
                ('pot', models.FloatField(default='', verbose_name='Pendapatan Orang Tua/Bulan (Rp)')),
                ('pre', models.FloatField(choices=[(0.55, '---Tidak Ada---'), (1.75, 'Regional'), (3.45, 'Nasional'), (5.5, 'Internasional')], default='', verbose_name='Prestasi (Pilih prestasi yang paling tinggi)')),
                ('bukti_prestasi', models.ImageField(default='', upload_to='upload/bukti_prestasi', verbose_name='Bukti Prestasi')),
                ('org', models.FloatField(choices=[(0.55, '---Tidak Ada---'), (1.75, 'Regional'), (3.45, 'Nasional'), (5.5, 'Internasional')], default='', verbose_name='Organisasi (Pilih organisasi yang tertinggi)')),
                ('bukti_organisasi', models.ImageField(default='', upload_to='upload/bukti_organisasi', verbose_name='Bukti Organisasi')),
                ('tgl_daftar', models.DateField(default='')),
                ('daftar', models.BooleanField(default=False)),
                ('akun', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
