# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-06 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_member',
            name='akun',
        ),
        migrations.DeleteModel(
            name='data_member',
        ),
    ]
